services:
  - type: web
    name: dma-discord-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DMA_MANUAL_GOOGLE_DOC_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_PATH
        sync: false
      - key: PORT
        value: 10000
